Quickstart 201: Copilot + Azure OAI
microsoft/power-platform-terraform-quickstarts pull request #108
Opened 2024-08-01 18:16 UTC by ianjensenisme

This pull request introduces a new quickstart example for deploying an OpenAI model to Azure, then connecting to it from  Copilot Studio as specified in #107 .

### Documentation Updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R43-L46): Added new quickstart example for `202-Copilot-deployment`.
* [`quickstarts/202-Copilot-deployment/README.md`](diffhunk://#diff-7962145cd51486af39b9dd77e2b044c61e49e8c2c52b6eab3c9b8963a2d66f00R1-R65): Added detailed documentation for deploying a Copilot to Copilot Studio, including prerequisites, provider requirements, usage instructions, and detailed behavior descriptions.
* [`quickstarts/202-Copilot-deployment/README.md.tmpl`](diffhunk://#diff-ea3d982602637b12c853c13bb1a227f32c26e5f3b79e4b1421d4d85128033042R1-R46): Added a template for the Copilot deployment documentation.

### Terraform Configuration:

* [`quickstarts/202-Copilot-deployment/azure/main.tf`](diffhunk://#diff-d800756b8a66a7ff2c3ded63a098f132ef2f4bd25816beb0c206edf6d9348a1eR1-R92): Added Terraform configuration for setting up Azure resources, including resource names, resource group, and OpenAI model deployment.
* [`quickstarts/202-Copilot-deployment/azure/output.tf`](diffhunk://#diff-0f4a546e0ffbe8ceb6c2bf3fd530a59343ad0e8976a4d78e589020c631d84c91R1-R7): Added output variables for the Power Platform environment name and Copilot name.
* [`quickstarts/202-Copilot-deployment/azure/variables.tf`](diffhunk://#diff-c62a654870bc5be7a2b7bae6b5c28fdccaa31737855a54a1fc2ce9d3f244cc91R1-R11): Added variables for Azure location and environment.
* [`quickstarts/202-Copilot-deployment/main.tf`](diffhunk://#diff-b5de49f6ec0ffd79faa3315bb3bb349d6a5c8256ea81c4a381313d40f00d2a8cR1-R35): Added main Terraform configuration to integrate Azure and Power Platform modules.
* [`quickstarts/202-Copilot-deployment/power-platform/main.tf`](diffhunk://#diff-ab051d8bebaa76fb1083c9b4e615dce4853d6e45e79dbc11b39c69348cab13feR1-R59): Added Terraform configuration for setting up Power Platform resources, including tenant settings, environment creation, and Dataverse record for the Copilot.
* [`quickstarts/202-Copilot-deployment/power-platform/variables.tf`](diffhunk://#diff-7471576a6e564dc3973f77d68fed6ddace215e0b12696b93b535d0eef499b665R1-R44): Added variables for Power Platform configuration, including project details, environment display name, and Copilot name.

2024-08-06 16:20 UTC, eduardodfmex requested changes
Let's update the provider version:  

version = "2.7.0-preview"


https://registry.terraform.io/providers/microsoft/power-platform/latest/docs

2024-08-06 16:20 UTC, eduardodfmex commented on quickstarts/202-Copilot-deployment/main.tf
> +      version = "2.6.2-preview"
You can use the latest version:
version = "2.7.0-preview"

2024-08-06 16:20 UTC, eduardodfmex commented on quickstarts/202-Copilot-deployment/power-platform/main.tf
> +      version = "2.6.2-preview"
You can use the latest version:
version = "2.7.0-preview"

2024-08-13 18:05 UTC, mattdot requested changes

2024-10-07 18:12 UTC, merged